export const defaultArchitectureGraph = {
  summary:
    'Autonomous AI Codebase Explainer & Visual Architect. Decoupled Spring Boot 3.3 REST API with JGit, AST Pruning Engine, and Google Gemini AI orchestration.',
  architecturePattern: 'Layered Architecture (N-Tier)',
  nodes: [
    {
      id: 'node-1',
      type: 'controllerNode',
      label: 'RepositoryController',
      filePath: 'src/main/java/com/architect/backend/controller/RepositoryController.java',
      startLine: 36,
      description: 'REST API endpoints for repository registration, analysis triggers, and snapshots.',
      tier: 'API',
    },
    {
      id: 'node-2',
      type: 'controllerNode',
      label: 'HealthController',
      filePath: 'src/main/java/com/architect/backend/controller/HealthController.java',
      startLine: 17,
      description: 'System health check and database connectivity verification endpoint.',
      tier: 'API',
    },
    {
      id: 'node-3',
      type: 'serviceNode',
      label: 'CodebaseAnalysisService',
      filePath: 'src/main/java/com/architect/backend/service/CodebaseAnalysisServiceImpl.java',
      startLine: 35,
      description: 'Asynchronous orchestrator executing on Java 21 Virtual Threads.',
      tier: 'BUSINESS_LOGIC',
    },
    {
      id: 'node-4',
      type: 'serviceNode',
      label: 'GitCloneService',
      filePath: 'src/main/java/com/architect/backend/service/GitCloneServiceImpl.java',
      startLine: 24,
      description: 'JGit shallow clone engine with AutoCloseable ephemeral storage purge.',
      tier: 'BUSINESS_LOGIC',
    },
    {
      id: 'node-5',
      type: 'serviceNode',
      label: 'GeminiAiService',
      filePath: 'src/main/java/com/architect/backend/service/GeminiAiServiceImpl.java',
      startLine: 27,
      description: 'Google Gemini 1.5/3.6 Flash API client with strict JSON schema decoding.',
      tier: 'BUSINESS_LOGIC',
    },
    {
      id: 'node-6',
      type: 'databaseNode',
      label: 'RepositoryEntity',
      filePath: 'src/main/java/com/architect/backend/model/RepositoryEntity.java',
      startLine: 30,
      description: 'PostgreSQL database entity for tracked repositories with UUID primary key.',
      tier: 'DATA_ACCESS',
    },
    {
      id: 'node-7',
      type: 'databaseNode',
      label: 'ArchitectureSnapshot',
      filePath: 'src/main/java/com/architect/backend/model/ArchitectureSnapshotEntity.java',
      startLine: 37,
      description: 'Versioned architectural snapshots stored as native PostgreSQL JSONB.',
      tier: 'DATA_ACCESS',
    },
  ],
  edges: [
    {
      id: 'e-1-3',
      source: 'node-1',
      target: 'node-3',
      label: 'triggers analysis',
      animated: true,
    },
    {
      id: 'e-3-4',
      source: 'node-3',
      target: 'node-4',
      label: 'shallow clone',
      animated: true,
    },
    {
      id: 'e-3-5',
      source: 'node-3',
      target: 'node-5',
      label: 'synthesizes graph',
      animated: true,
    },
    {
      id: 'e-3-7',
      source: 'node-3',
      target: 'node-7',
      label: 'persists JSONB',
      animated: true,
    },
    {
      id: 'e-1-6',
      source: 'node-1',
      target: 'node-6',
      label: 'persists metadata',
      animated: true,
    },
  ],
};
